### ISSUE TITLE
can't run nyzoVerifier

### ISSUE THREAD

**Issue by viteshan** [n-y-z-o/nyzoVerifier#4]
I try to run nyzoVerifier by 'java -jar -Xmx3G xxx/nyzoVerifier/build/libs/nyzoVerifier-1.0.jar', but it seems that nothing happened.

and i try to analyze what it happened by "jstack -l pid"

and i get the result, it seems to be blocking when generating the private key.

"main" #1 prio=5 os_prio=0 tid=0x00007f528804b800 nid=0x307f runnable [0x00007f528ee05000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at sun.security.provider.NativePRNG$RandomIO.readFully(NativePRNG.java:424)
	at sun.security.provider.NativePRNG$RandomIO.getMixRandom(NativePRNG.java:404)
	- locked <0x00000000c051ed08> (a java.lang.Object)
	at sun.security.provider.NativePRNG$RandomIO.implNextBytes(NativePRNG.java:534)
	at sun.security.provider.NativePRNG$RandomIO.access$400(NativePRNG.java:331)
	at sun.security.provider.NativePRNG$Blocking.engineNextBytes(NativePRNG.java:268)
	at java.security.SecureRandom.nextBytes(SecureRandom.java:468)
	at net.i2p.crypto.eddsa.KeyPairGenerator.generateKeyPair(KeyPairGenerator.java:75)
	at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:697)
	at co.nyzo.verifier.KeyUtil.generateSeed(KeyUtil.java:130)
	at co.nyzo.verifier.Verifier.loadPrivateSeed(Verifier.java:100)
	- locked <0x00000000c04d1c18> (a java.lang.Class for co.nyzo.verifier.Verifier)
	at co.nyzo.verifier.Verifier.<clinit>(Verifier.java:49)

**Comment by viteshan** [comment]
I found the reason, the process can't get random numbers by /dev/random.
And this command(cat  /dev/random | head -n 10 | od -x) verifies my guess.
the solution:
> sudo systemctl start haveged
